name: GEASHilfe
options:
  bundleIdPrefix: de.polizei.sachsen.leipzig
  deploymentTarget:
    iOS: "16.0"
  developmentLanguage: de
settings:
  base:
    MARKETING_VERSION: "2.1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    TARGETED_DEVICE_FAMILY: "1,2"
targets:
  GEASHilfe:
    type: application
    platform: iOS
    sources:
      - path: GEASHilfe
      - path: ../content/content.json
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: de.polizei.sachsen.leipzig.geashilfe
        INFOPLIST_KEY_CFBundleDisplayName: "GEAS Hilfe"
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_ITSAppUsesNonExemptEncryption: NO
        GENERATE_INFOPLIST_FILE: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
